-- =============================================================================
-- User Web Push subscriptions
-- =============================================================================
-- Stores browser push subscriptions for STUDENT/USER devices, separately from the
-- admin `push_subscriptions` table.
--
-- Why a separate table:
--   `sendPushToAdmins()` sends "New Order" to EVERY row in `push_subscriptions`.
--   If user devices lived in that table they would receive admin alerts. Keeping
--   user subscriptions here guarantees the admin and user push systems never
--   cross-notify and can operate fully independently.
--
-- Structure mirrors `public.push_subscriptions`. Additive & idempotent — safe to
-- run on the live database (creates a brand-new table, touches nothing existing).

CREATE TABLE IF NOT EXISTS public.user_push_subscriptions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  endpoint   TEXT UNIQUE NOT NULL,
  keys       JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- sendPushToUser() filters by user_email; index it for fast lookups.
CREATE INDEX IF NOT EXISTS user_push_subscriptions_user_email_idx
  ON public.user_push_subscriptions (user_email);

-- Only the backend (service role, which bypasses RLS) reads/writes this table.
-- Enabling RLS with no permissive policy denies all anon/authenticated client
-- access, matching the locked-down posture of the rest of the schema.
ALTER TABLE public.user_push_subscriptions ENABLE ROW LEVEL SECURITY;
